[[pages]]
path = "pages/1_home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Barcelona"
icon = "ğŸŒ†"
is_section = true

[[pages]]
path = "pages/Barcelona.py"
name = "Overview"
icon = "ğŸ“„"

[[pages]]
path = "pages/Barcelona Kepler.py"
name = "Kepler Map"
icon = "ğŸ—ºï¸"

[[pages]]
path = "pages/Barcelona Plotly.py"
name = "Plotly Charts"
icon = "ğŸ“Š"

[[pages]]
name = "Gothenburg"
icon = "ğŸ™ï¸"
is_section = true

[[pages]]
path = "pages/Gothenburg.py"
name = "City Overview"
icon = "ğŸ“"

[[pages]]
name = "Hide this"
icon = "ğŸš«"
is_section = true

[[pages]]
path = "pages/2_pilot.py"
name = "Pilot"
icon = "ğŸš«"