[[pages]]
path = "pages/1_home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/Barcelona.py"
name = "Overview"
icon = "ğŸ“„"

[[pages]]
path = "pages/Barcelona Kepler.py"
name = "Kepler Map"
icon = "ğŸ—ºï¸"

[[pages]]
path = "pages/Barcelona Plotly.py"
name = "Plotly Charts"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Gothenburg.py"
name = "City Overview"
icon = "ğŸ“"


